import { useChannel } from 'hooks/useChannel';
import type { NextPage } from 'next';
import Head from 'next/head';
import { AppEvents } from 'app/events';

import styles from './Home.module.css';
import { Job } from 'app/types';
import JobList from 'components/JobList';
import ScheduleJobForm from 'components/ScheduleJobForm';
import { scheduleJob } from 'services/email-worker.service';

const Home: NextPage = () => {
    const { data } = useChannel<Job[]>({ event: AppEvents.JobUpdated });

    const handleSubmit = async (count: number) => {
        await scheduleJob(count);
    };

    return (
        <>
            <Head>
                <title>Jobs App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <ScheduleJobForm onSubmit={handleSubmit} />
                <br />
                {!!data?.length && <JobList jobs={data} />}
            </main>
        </>
    );
};

export default Home;
