version: '3'

services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        volumes:
            - zookeper_data:/var/lib/zookeeper/data
    kafka:
        image: 'bitnami/kafka:latest'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        volumes:
            - kafka_data:/bitnami/kafka
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password1@
            - MYSQL_DATABASE=email-worker
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - mysql_data:/var/lib/mysql
    app:
        image: email-worker:latest
        environment:
            - DATABASE_URL=mysql://root:password1@@db:3306/email-worker
            - KAFKA_CLIENT_ID=email-worker
            - KAFKA_BROKERS=kafka:9092
            - KAFKA_CONSUMER_GROUP_ID=email_handler
        ports:
            - 3000:3000
        depends_on:
            - db

volumes:
    zookeper_data:
    kafka_data:
    mysql_data:

networks:
    app-tier:
        driver: bridge
