version: '3'

services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        volumes:
            - zookeper_data:/var/lib/zookeeper/data
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        volumes:
            - kafka_data:/bitnami/kafka
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password1@
            - MYSQL_DATABASE=email-worker
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    zookeper_data:
    kafka_data:
    mysql_data:

networks:
    app-tier:
        driver: bridge
